
services:

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ../docker/srcs/frontend/Dockerfile
      args:
        IP: ${IP}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    restart: always
    networks:
      - transcendence

  postgres:
    image: postgres
    container_name: postgres
    build:
      context: ./docker/srcs/postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=${POSTGRES_PASSWORD} pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 50s

networks:
  transcendence:
    driver: bridge

volumes:
  db_data:
    driver: local