
services:

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ../docker/srcs/frontend/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - .env
    # DEV ONLY: remove these 2 lines before evaluation so code runs from the Docker image
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
    networks:
      - transcendence

  postgres:
    image: postgres
    container_name: postgres
    build:
      context: ./docker/srcs/postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d transcendence"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  transcendence:
    driver: bridge

volumes:
  db_data:
    driver: local